# http://travis-ci.org/#!/jupyter/jupyterdrive
language: python
python:
    - 3.4
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse -r requirements.txt coveralls
    - pip install -e .
    - pip install -f pytest
script:
    - py.test
after_success:
    - coveralls
